name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"
      - name: Build
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/goSlow-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: goSlow-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/goSlow-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/**/goSlow-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
